<?php

namespace OM\OddsMatrix\SEPC\Connector\Enum;

class EnvVars
{
    public const DECODED_SOCKET_DIRECTORY_PATH = 'SEPC_DECODED_SOCKET_DIRECTORY_PATH';
    public const CONNECTOR_PROFILING_LOGS = 'SEPC_CONNECTOR_PROFILING_LOGS';
    public const PUSH_BRIDGE_VERBOSE_LOGS_ENABLED = 'SEPC_PUSH_BRIDGE_VERBOSE_LOGS_ENABLED';
    public const RAW_SOCKET_OUTPUT_FILE = 'SEPC_RAW_SOCKET_OUTPUT_FILE';
}